[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
ssh2 = "0.9.4"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
rpassword = "7.3.1"
chrono = "0.4.38"
